services:
  loki:
    container_name: loki
    image: grafana/loki
    volumes:
      - /home/ubuntu/docker_volumes/loki:/etc/loki
    ports:
      - "3100:3100"
    restart: unless-stopped
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - loki

  promtail:
    container_name: promtail
    image: grafana/promtail
    volumes:
      - /var/log:/var/log
      - /home/ubuntu/docker_volumes/promtail:/etc/promtail
    # ports:
    #   - "1514:1514" # this is only needed if you are going to send syslogs
    restart: unless-stopped
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - loki

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    user: "1000"
    volumes:
    - /home/ubuntu/docker_volumes/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - loki

networks:
  loki:        
