version: '3.5'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
       proxy:
    ports:
      - 80:80
      - 443:443
    environment:
      - CF_API_EMAIL=<EMAIL_ADDR>
      - CF_DNS_API_TOKEN=<CF_API_KEY>
      # - CF_API_KEY=YOU_API_KEY
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/ubuntu/docker/traefik/traefik.yml:/traefik.yml:ro
      - /home/ubuntu/docker/traefik/acme.json:/acme.json
      - /home/ubuntu/docker/traefik/config.yml:/config.yml:ro
      - /home/ubuntu/docker/traefik/logs:/var/log/traefik
    labels:
      # Enable Traefik for this service
      - "traefik.enable=true"
      # HTTP Router configuration
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik-dashboard.xsec.in`)"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      # Middleware for HTTP to HTTPS redirection
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      # Middleware for custom headers
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      # HTTPS Router configuration with authentication
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik-dashboard.xsec.in`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=cloudflare"
      # TLS configuration for domain and subdomains
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=xsec.in"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.xsec.in"
      # Internal service configuration for the Traefik dashboard API
      - "traefik.http.routers.traefik-secure.service=api@internal"
      # Basic authentication middleware (credentials set with htpasswd)
      # echo $(htpasswd -nb "admin" "tf2vrJDtyA3IPrrNI9Sj") | sed -e s/\\$/\\$\\$/g
      - "traefik.http.middlewares.traefik-auth.basicauth.users=<CREDS-FROM-httpasswd>"
networks:
  proxy:
    name: proxy
    external: true
